cameronsutter/plottr_electron

- src/app/components/timeline/BlankCard.js
The blank card was not handling card drops properly.
Switched to use the same action as the SceneCards
was using to move cards around
refs: BUG-70
> Fixed broken ordering in outline and export

- src/common/slate_serializers/from_html.js
fixes: BUG-51
Pasting and matching style worked for me how I would expect it to. But there was a bug with pasting into the RCE and it losing its original styling which this fixes. So I'm not sure if this fixes the issue that the task was identifying but it was a bug nonetheless.
There is still an issue with slate where copying text within a mark doesn't capture the HTML for the mark itself.
https://github.com/ianstormtaylor/slate/issues/734
> Fix pasting rich content into RCE

- src/app/components/story/BookList.js
- src/css/book.scss
Fixes problem where books couldn't be dragged between rows of books in the BookList.
When there are enough books, the display wraps books which don't fit on a single line onto the next.  `react-beautiful-dnd` is designed to handle a single row or column and fails to meet our need of dragging books in a flex-grid layout.
This problem is documented on Github: (https://github.com/atlassian/react-beautiful-dnd/issues/316).
There is mention of a plan to fix it, but, for the interim, a workaround is required.
Other libraries exist which handle our use case.
This is a good alternative and is worth considering as an alternative to this PR https://www.npmjs.com/package/react-grid-dnd.  I've used the library before and can confirm that it works for our use case.
As documented in …
> Bugfix drag and drop between rows in book list

- package-lock.json
- package.json
- src/app/store/configureStore.js
This is a quick PR to add remote dev tools to the `configureStore` function.
It works by connecting to a local remote-devtools server.
I find it crucial to be able to inspect the redux store and replay events to debug and understand redux applications.
In `package.json`, there's a new script to launch the server, run `npm` like so: `npm run start-redux-dev-tools`.
Then start your browser and launch the remote dev tools from it using the extensions context menu.
Finally, use `settings` in the dev tools popup to configure the remote dev tools to point at `localhost:8000`.
For the time being, there appears to be one redux store, so this works fine.
If we create more redux stores in the future, then we'll need to figure out a way to create multiple distinct sockets.
> Add remote redux dev tools setup

- package.json
- webpack.config.js
The build for Windows was broken in: https://github.com/cameronsutter/plottr_electron/commit/d24e11019a4cf34afd33baf3d3d43e4f8835695a
See: https://ci.appveyor.com/project/cameronsutter/plottr-electron/builds/37389134
I reproduced the problem locally:
```
Entrypoint app = commons.bundle.js commons.map app.bundle.js app.map
Entrypoint css = css.bundle.js css.map
Entrypoint dashboard = reactIcons.bundle.js reactIcons.map commons.bundle.js commons.map dashboard.bundle.js dashboard.map
[8] external "require(\"electron\")" 42 bytes {1} {3} [built]
[9] external "path" 42 bytes {1} {3} [built]
[10] external "fs" 42 bytes {1} {3} [built]
[33] ./common/utils/settings.js 613 bytes {0} [built]
[45] ./common/utils/MPQ.js 3.22 KiB {0} [built]
[97] ./common/utils/rollbar.js 2.31 KiB {0} [built]
[160] …
```
> Fix the build

- src/app/components/timeline/CardDialog.js
Create a new blank card and chapter by clicking on the plus icon next to a card.
Open the card for editing.
Close the card.
Result: an exception is thrown.
The feature to add a blank card when inserting in between cards creates cards without template values.
The fix (use an empty array if templates aren't present) is a bandage over this and similar causes of the problem because we aim to remove the feature of adding a blank card soon anyway.
> Release Bug Fix: blank cards error on close

- src/app/components/dialogs/CustomAttributeModal.js
- src/app/reducers/cards.js
When custom attributes were added to scenes, the edit functionality didn't account for the fact that attributes already exist on some cards.
This branch ensures that existing data is migrated to the new name.
Some of the functionality around this and other similar attributes related functions in the reducers are starting to look very similar.
We might want to consider extracting that logic as a refactor or when touching these reducers in the future.
> Migrate data when editing custom attributes for scenes

- src/app/components/timeline/CardDialog.js
This removes the call to save in `componentWillUnmount`.
It has the knock-on effect of not double saving when we hit `save`.
Hitting `esc` still saves and closes.
Is that desirable?
After @cameronsutter 's comments, the implementation changed.
It now uses a piece of state to flag that we're unmounting and deliberately preventing a save.
i.e. the default behaviour is to save when the component unmounts.
It will only *not* save when asked to.
> Don't save attributes on scenes when cancelling the dialog

- jest.config.js
- package.json
- src/app/reducers/__tests__/cards.test.js
- src/app/reducers/__tests__/customAttributes.test.js
- src/app/reducers/cards.js
The cards reducer is not covered by tests and contains some of the apps most important logic.
1. Custom attributes were added to cards without test coverage.
2. We might want to refactor it in due course and tests would help with that.
1. Singleton state produced when adding to an undefined state.  Previously the reducer would error in this case.  We never ran into it because redux initialises the reducer with an unknown event.  It still seems prudent to have a default state value.
2. The position of a card in a chapter is inferred when not supplied.  Previously we relied on the components to provide both the card ordering in `reorderIds` *and* the position of the new card.  The reducer now looks for the position of `null` in `reorderIds` to determine the position of the card in the …
> Add tests for latest features

- .gitignore
- package-lock.json
- package.json
- shared/initialState.js
- src/app/components/EditAttribute.js
- src/app/components/characters/CharacterEditDetails.js
- src/app/components/story/BookList.js
- src/app/components/timeline/AddLineRow.js
- src/app/components/timeline/BlankCard.js
- src/app/components/timeline/CardDialog.js
- src/app/components/timeline/LineTitleCell.js
- src/app/components/timeline/SceneCardAdd.js
- src/app/components/timeline/ScenesCell.js
- src/app/components/timeline/TimelineTable.js
- src/app/components/timeline/TopRow.js
- src/app/reducers/main.js
- src/app/reducers/seriesLines.js
- src/app/store/lineColors.js
- src/common/components/templates/SceneTemplateDetails.js
- src/common/components/templates/TemplatePicker.js
- src/common/importer/snowflake/importer.js
- src/common/utils/custom_templates.js
- src/css/card_block.css.scss
To enable users to create scene cards from custom attribute templates.
This branch adds UI elements for creating a new card with a template and picking a scene template.
I copied the way that plotlines are created with templates so that:
- when you hover of a blank card you see a split button (like plotlines);
- when you click on the plus icon, we enter the original flow for creating a scene card (i.e. title form appears).
- when you click on "Use Template" it opens the template picker and when you've picked a template, it advances to the title input form and remembers the template selection.
We now have a `SceneTemplateDetails` component wired up to the Template picker when scene templates are selected.
The following changes were made to the plumbing to support the UI changes:
- Reducers …
> Enable templates for scene creation

- package.json
Building for both Linux and MacOS means that you need credentials for MacOS apps to build a Linux app.
This branch adds the command: `npm run dist:linux` to build for only Linux.
> Add a Linux target to avoid having to set apple credentials

- bin/new_main.js
At the moment the project watches everything in the root except for src and a few others.
When you run dist this means that there are thousands of files to watch.
This is also a problem since merging `pltr` into `plottr_electron` because watchers are spawned for all the source files and node modules in that subtree too(!).
We now watch only the root files of `plottr_electron` (I couldn't find a way to avoid that because when I added an exclusion for it it also excluded `bin`) and the `bin` folder for changes.
This makes development lighter on the system.
> Ignore everything that we can

- package-lock.json
- package.json
- src/app/components/rce/Element.js
- src/app/components/rce/__tests__/links.test.js
When a link is rendered, we used `#` for the `href` attribute.
This points the DOM's model of the link at the page in Electron.
We need this because Right Click -> Copy Link uses the DOM element.
> Fix href for rce links

- README.MD
- package.json
- src/app/components/rce/RichTextEditor.js
This PR fixes KAN-116:
- open a card dialog,
- click anywhere on the editable region which doesn't yet contain text,
- the editor isn't focus for text insertion.
Use the ref to the editor's editable dom node to focus the editor's first child element when we detect a click which isn't contained by the first child.
I tried to implement a test for this problem, but ran into problems.
There are discussions about doing this properly, and the methods of testing appear to work for some people and not others.
I tried to detect when the document's current focus changes after simulating a click.
It appears to not have worked.
I feel like this might be too flaky to add as a test at this time.
This is the non-working test.
Suggestions for a better test welcome!
```javascript
import React from 'react' …
```
> Kan 116 rce click to focus editor

- src/app/components/images/ImagePicker.js
This is a hack.  It fixes the problem in the short term.  I recommend that more time is provisioned to investigate further.
If the user opens a card dialogue and then opens the image picker, then the RCE opens another modal on top of the card modal.
If the user goes to the image from URL tab then the input field is non-interactive.
I suspect that focus is actually being stolen by the modal which the image picker model is on top of.
There's a mousedown event which appears to steal focus (if I delete it the event handler from the developer tools then focus works as expected and the user can enter text into the input field).
I recommend that this hack be removed when we track down where the mousedown event comes from.
> Hack: focus the form element when it's clicked

- lib/pltr/v2/reducers/beats.js
- lib/pltr/v2/reducers/cards.js
- lib/pltr/v2/reducers/lines.js
I'm not sure whether the behaviour outlined in the heading is intended.
If `DELETE_BOOK` is supposed to delete a book along with it's associated data, then this PR accomplishes that.
> Remove lines, beats and cards associated to deleted book

- src/common/utils/custom_templates.js
Otherwise, templates create dangling cards, and the user might have a confusing time trying to create single-line templates.
> Use all lines when creating a custom template

- lib/pltr/v2/template/index.js
- src/common/components/templates/PlotlineTemplateDetails.js
- src/common/components/templates/TemplatePicker.js
- src/dashboard/components/files/FilesHome.js
Previous versions of `plottr` supported exporting without a line and applied a template by creating a line with a title that equalled the template's title.
The problem with doing this is that it's hard to migrate partial templates.
A previous commit ensured that templates are created with a line.
Partial templates could still exist in user's templates files.
So this PR supports that case by special-casing the application of templates to new timelines.
> Special case applying a template for a line rather than the project

- lib/pltr/package.json
Changes `plottr_locales` to a peer dependency in `pltr`.
> Depend on plottr_locales instead of format-message from pltr

- lib/pltr/v2/reducers/beats.js
The problem seems to have originated in the refactoring to merge beats and chapters.
Beats could only be manually sorted if they were associated with a series.
Now beats are associated with series and books so the check is incorrect.
> Always allow beats to become manually sorted

- lib/pltr/v2/helpers/__tests__/lists.test.js
- lib/pltr/v2/helpers/lists.js
- lib/pltr/v2/reducers/beats.js
- package.json
After adding one or more beats to the timeline and then deleting a beat, the beats are repositioned in the wrong order.
This happens because the old `DELETE_BEAT` action ran a `positionReset` on the beats after filtering out the deleted beat.
`positionReset` changes the order of the beats to the order that they appear in the array rather than their `position`s(!)
When a beat is added to the timeline, we prepend it.
So, when we delete a beat, the beats aren't sorted, and the beats with correct `position`s but positions in the array of beats that don't correspond to their `position`s are placed wherever they are in the array.
First, sort the beats before re-ordering.
Note: The `positionReset` function is used elsewhere to set the ordering of beats to a given ordering, so we don't want to …
> Fix delete beat bug
