- bin/about.html
- src/app/actions/characters.js
- src/app/actions/places.js
- src/app/components/characters/characterView.js
- src/app/components/places/placeView.js
- src/app/reducers/characters.js
- src/app/reducers/places.js
- src/app/store/initialState.js
I fixed issue 69. Please review?
> Dev: Issue 69 fix

- src/app/components/timeline/cardView.js
- src/app/components/timeline/lineListView.js
- src/app/components/timeline/lineView.js
- src/app/components/timeline/sceneListView.js
- src/app/components/timeline/sceneView.js
- src/app/components/timeline/timeLineView.js
> Fix zoom popover effect scale

- src/css/darkmode.scss
bug squashing live! (fixed darkmode modal content background color - line 76)
> Update darkmode scss

- src/app/components/characters/CustomAttributeModal.js
- src/css/darkmode.scss
>  [custom attributes dialog] still in dark mode after returning to normal

- src/app/components/tag/tagView.js
Adding new tag, ink button now working on immediate hover (as opposed to move away and come back)
> fixed bug-18

- package-lock.json
- src/app/components/rce/BlockButton.js
- src/app/components/rce/Normalizer.js
- src/app/components/rce/RichTextEditor.js
- src/app/components/rce/helpers.js
- src/app/components/rce/withList.js
- src/app/components/timeline/CardDialog.js
- src/css/card_dialog.css.scss
Also fixes long chapter and line titles on modal
> Fix numbered and bulleted lists

- package-lock.json
- package.json
> Upgrade slate-react to get proper newline pasting behavior

- src/common/exporter/scrivener/v2/exporter.js
refs: BUG-60, BUG-58
It would be good to test this in Scrivener instead of just
a document viewer like Word
> Convert unicode characters for rendering in RTF

- src/app/reducers/cards.js
> Remove cards on series and beat delete

- src/app/components/rce/BlockButton.js
- src/app/components/rce/helpers.js
In fixing lists, I broke these other types
> Fix bug with title, subtitle, and block quote

- src/app/components/rce/RichTextEditor.js
- src/app/components/rce/editor-registry.js
- src/app/index.js
> Make menu undo/redo work on rce

- bin/main.js
- bin/main_modules/menus/file.js
- src/dashboard/index.js
- src/expired/index.js
- src/verify/index.js
Some of these won't be relevant after the language selection PR but they were broken none the less.
> A few fixes from the main.js refactor

- src/css/book.scss
> Put a max height on book cover images

- .babelrc
- babel.config.js
- jest.config.js
- locales/index.js
- package-lock.json
- package.json
- src/app/components/dialogs/InputModal.js
- src/app/components/dialogs/__tests__/InputModal.test.js
- test/getTestIds.js
- test/setupTests.js
- test/test-utils/getTestIds.js
- webpack.config.js
I'm requesting review for this one. Once it is merged I will just write tests and commit them to master.
> Introduce unit testing

- package-lock.json
- src/css/book.scss
- src/dashboard/components/navigation/DashboardBody.js
> Extend scroll area to include whole book container

- .eslintrc.js
- .prettierrc
- jest.config.js
- package-lock.json
- package.json
- src/app/selectors/characters.js
- src/app/selectors/notes.js
- src/app/selectors/places.js
- src/common/exporter/scrivener/v2/__tests__/utils.test.js
- src/common/exporter/scrivener/v2/bare_scrivx.json
- src/common/exporter/scrivener/v2/exporter.js
- src/common/exporter/scrivener/v2/exporters/__tests__/chapters.test.js
- src/common/exporter/scrivener/v2/exporters/__tests__/characters.test.js
- src/common/exporter/scrivener/v2/exporters/__tests__/fixtures/index.js
- src/common/exporter/scrivener/v2/exporters/__tests__/fixtures/test_state.json
- src/common/exporter/scrivener/v2/exporters/__tests__/notes.test.js
- src/common/exporter/scrivener/v2/exporters/__tests__/places.test.js
- src/common/exporter/scrivener/v2/exporters/chapters.js
- src/common/exporter/scrivener/v2/exporters/characters.js
- src/common/exporter/scrivener/v2/exporters/notes.js
- src/common/exporter/scrivener/v2/exporters/places.js
- src/common/exporter/scrivener/v2/utils.js
- src/common/slate_serializers/to_rtf.js
- src/common/slate_serializers/to_word.js
Also fixes a bug with unicode conversion for rtf
Fixes a bug with headings not showing up in rtf documents
Fixed eslint and prettier conflict with spaces before function parens
Fixes scrivener exports for lists
fixes: KAN-12
> Add support for exporting characters, notes, and places

- src/app/components/timeline/CardDialog.js
An obvious mistake here with a one-line fix.
> Wire up the correct actions for custom attributes

- src/app/components/timeline/AddLineRow.js
- src/common/importer/snowflake/importer.js
Fix an incorrect import in two places.
> Use the nextColor function from lineColors from pltr v2

- src/app/components/timeline/AddLineRow.js
Just as easy to add the functionality to the original if/else statement, but it made the two parts identical so I just cleared out the if/else. Let me know if that's not what you had in mind.
> added Use Template function to Series View

- src/app/containers/ErrorBoundary.js
- src/css/error_boundary.scss
Regular old $text-color was the right match since the dark mode color was making it white on white
> new branch adjusting darkmode error and no package weirdness

- src/app/components/dialogs/ItemsManagerModal.js
One question was whether to set restrictedValues to allow objects as well as arrays.. I set it just to objects and it seems to work well enough but do you think that'd be necessary?
> adjusted propTypes for bug KAN-191

- src/app/components/MiniColorPicker.js
- src/app/components/rce/RichTextEditor.js
- src/app/components/timeline/CardDialog.js
- src/css/color_picker_block.css.scss
> kan-223 added mini-colorpicker darkmode bgcolor

- src/app/components/timeline/AddLineRow.js
> kan-241 reverted back input modal to text input
